In [1]:
from scipy.io import wavfile
from scipy.fftpack import fft
import numpy as np

from find_note import find_note
from write_midi import write_file
from compress_notes import compress_notes

In [2]:
audio_file = wavfile.read("random.wav")
sample_rate = audio_file[0]
signal = np.array(audio_file[1])
signal = signal[:, 0]

In [3]:
signal

array([4, 4, 4, ..., 0, 0, 0], dtype=int16)

In [4]:
blocks = []
start = 0
end = int(sample_rate/15)
while end <= len(signal):
    blocks.append(signal[start: end])
    start += int(sample_rate/60)
    end += int(sample_rate/60)

In [5]:
blocks[: 5]

[array([   4,    4,    4, ..., 1659, 1619, 1563], dtype=int16),
 array([-1099, -1013,  -994, ...,  2924,  3057,  3089], dtype=int16),
 array([  -56,  -426,  -731, ..., -1232, -1508, -1773], dtype=int16),
 array([ 2601,  2892,  3059, ..., -3109, -2995, -2935], dtype=int16),
 array([ 1524,  1527,  1566, ..., -1434, -1258, -1085], dtype=int16)]

In [6]:
freqs = []
for b in blocks:
    fourier = abs(fft(b))
    freqs.append(np.argmax(fourier) * 15)

In [7]:
notes = []
for freq in freqs:
    notes.append(find_note(freq))

In [8]:
notes

[['F#4/Gb4', 369.99, 66],
 ['F#4/Gb4', 369.99, 66],
 ['F#4/Gb4', 369.99, 66],
 ['F#4/Gb4', 369.99, 66],
 ['F#4/Gb4', 369.99, 66],
 ['F#4/Gb4', 369.99, 66],
 ['F#4/Gb4', 369.99, 66],
 ['F#4/Gb4', 369.99, 66],
 ['F#4/Gb4', 369.99, 66],
 ['F#4/Gb4', 369.99, 66],
 ['F#4/Gb4', 369.99, 66],
 ['F#4/Gb4', 369.99, 66],
 ['F#4/Gb4', 369.99, 66],
 ['F#4/Gb4', 369.99, 66],
 ['F#4/Gb4', 369.99, 66],
 ['F#4/Gb4', 369.99, 66],
 ['F#4/Gb4', 369.99, 66],
 ['F#4/Gb4', 369.99, 66],
 ['B4', 493.88, 71],
 ['B4', 493.88, 71],
 ['B4', 493.88, 71],
 ['B4', 493.88, 71],
 ['B4', 493.88, 71],
 ['B4', 493.88, 71],
 ['B4', 493.88, 71],
 ['B4', 493.88, 71],
 ['B4', 493.88, 71],
 ['B4', 493.88, 71],
 ['B4', 493.88, 71],
 ['B4', 493.88, 71],
 ['B4', 493.88, 71],
 ['B4', 493.88, 71],
 ['B4', 493.88, 71],
 ['B4', 493.88, 71],
 ['B4', 493.88, 71],
 ['B4', 493.88, 71],
 ['B4', 493.88, 71],
 ['B4', 493.88, 71],
 ['A4', 440, 69],
 ['A4', 440, 69],
 ['A4', 440, 69],
 ['A4', 440, 69],
 ['A4', 440, 69],
 ['A4', 440, 69],
 ['A

In [9]:
compressed = compress_notes(notes)

In [10]:
compressed

[['B4', 493.88, 71],
 ['A4', 440, 69],
 ['E4', 329.63, 64],
 ['F#4/Gb4', 369.99, 66],
 ['F4', 349.23, 65],
 ['G#4/Ab4', 415.3, 68],
 ['G4', 392, 67]]

In [11]:
write_file(compressed, 1, 180)